### ISSUE TITLE
Update the C2LC website footer

### ISSUE THREAD

**Issue by sepidehshahi** [codelearncreate/c2lc-website#53]
Please make the following changes on the C2LC website footer:

- Remove the social media icons
- Add IRIS institute logo 
- Change the first sentence to Coding to Learn and Create is led by the Inclusive Design research Centre at OCAD University, The IRIS Institute, and Bridges Canada.
- Link all the organizations

1. IDRC: https://idrc.ocadu.ca/
2. OCAD U: https://www.ocadu.ca/
3. IRIS: https://irisinstitute.ca/
4. Bridges: https://www.bridges-canada.com/

**Comment by michelled** [comment]
Fixed through https://github.com/codelearncreate/c2lc-website/pull/57
